version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3306:3306'

  db_admin:
    image: adminer
    container_name: db_admin
    ports:
      - '9090:8080'
    depends_on:
      - db